name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and test
      run: |
        npm install
        npm test
        echo "Done"
      env:
        CI: true
